spring:
  application:
    name: soundCloud-BE
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  cache:
    type: caffeine
    caffeine:
      spec: maximumSize=500,expireAfterWrite=1h

firebase:
  service-account-path: ${FIREBASE_SERVICE_ACCOUNT_PATH}

spotify:
  client:
    id: ${SPOTIFY_CLIENT_ID}
    secret: ${SPOTIFY_CLIENT_SECRET}

lyrics:
  ovh:
    baseUrl: https://api.lyrics.ovh/

app:
  music:
    storage:
      path: ${APP_MUSIC_STORAGE_PATH:music-downloads}

ytdlp:
  auto-install: true
  executable-path: ${YTDLP_EXECUTABLE_PATH:}
ffmpeg:
  executable-path: ${FFMPEG_EXECUTABLE_PATH:}