spring:
  application:
    name: soundCloud-BE
  datasource:
    url: jdbc:mysql://localhost:3306/soundcloud_db
    username: root
    password: quannguyen2004

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
